"""Focused tests for the reusable Streamlit report components."""

from __future__ import annotations

import ui.components as components


class _Context:
    def __enter__(self):
        return self

    def __exit__(self, *_args):
        return False


class _Column:
    def __init__(self, events: list[tuple]) -> None:
        self.events = events

    def metric(self, label, value) -> None:
        self.events.append(("metric", label, value))

    def write(self, value) -> None:
        self.events.append(("write", value))


class _FakeStreamlit:
    def __init__(self) -> None:
        self.events: list[tuple] = []

    def markdown(self, value) -> None:
        self.events.append(("markdown", value))

    def caption(self, value) -> None:
        self.events.append(("caption", value))

    def info(self, value) -> None:
        self.events.append(("info", value))

    def write(self, value) -> None:
        self.events.append(("write", value))

    def divider(self) -> None:
        self.events.append(("divider",))

    def expander(self, label, *, expanded=False):
        self.events.append(("expander", label, expanded))
        return _Context()

    def columns(self, count):
        return [_Column(self.events) for _ in range(count)]


def _material() -> dict:
    return {
        "topic": "Recursion",
        "title": "Base cases",
        "explanation": "A base case stops recursive calls.",
        "analogy": "A staircase with a ground floor.",
        "common_mistake": "Forgetting to move toward the base case.",
        "self_test": "What makes each call smaller?",
        "prerequisites": ["Functions"],
        "rationale": {
            "why_shown": "A saved quiz answer missed this topic.",
            "quiz_evidence": "One high-confidence incorrect answer.",
            "generation_source": "Generated by the Resource Agent.",
        },
    }


def test_resource_materials_use_loader_and_render_details(monkeypatch):
    fake_st = _FakeStreamlit()
    monkeypatch.setattr(components, "st", fake_st)

    shown = components.render_resource_material_suggestions(
        ["Recursion"],
        caption="Based on saved answers.",
        suggestion_loader=lambda _topics: [_material()],
    )

    assert shown is True
    assert ("markdown", "### Suggested Resource Materials") in fake_st.events
    assert ("caption", "Based on saved answers.") in fake_st.events
    assert any(
        event[:2] == ("write", "A base case stops recursive calls.") for event in fake_st.events
    )


def test_empty_resource_materials_show_explanation(monkeypatch):
    fake_st = _FakeStreamlit()
    monkeypatch.setattr(components, "st", fake_st)

    shown = components.render_resource_material_suggestions(
        ["Recursion"],
        empty_message="No materials saved yet.",
        suggestion_loader=lambda _topics: [],
    )

    assert shown is False
    assert ("info", "No materials saved yet.") in fake_st.events


def test_quiz_snapshot_renders_metrics_evidence_and_saved_materials(monkeypatch):
    fake_st = _FakeStreamlit()
    monkeypatch.setattr(components, "st", fake_st)
    session = {
        "course": "Intro to CS",
        "created_at": "2026-08-19T12:00:00+00:00",
        "question_count": 1,
        "correct": 0,
        "accuracy": 0,
        "summary": "Review the missed concept.",
        "strengths": "The student recognized the function call.",
        "priority_feedback": "Review Recursion.",
        "confidence_feedback": "High-confidence miss.",
        "next_step": "Practice one base-case question.",
        "priority_topics": ["Recursion"],
        "resource_materials": [_material()],
        "rows": [
            {
                "number": 1,
                "topic": "Recursion",
                "correct": False,
                "difficulty": 3,
                "confidence": 5,
                "signal": "Misconception",
                "question": "What stops recursion?",
                "student_answer": "B",
                "correct_answer": "A",
                "explanation": "A base case stops recursion.",
                "feedback_summary": "Review the termination condition.",
                "confidence_insight": "Confidence did not match the result.",
                "resource_note": "Resource material requested.",
                "review_note": "Due tomorrow.",
                "next_action": "Retry at difficulty 2.",
            }
        ],
    }

    components.render_quiz_session_snapshot(session, expanded_rows=True)

    assert ("metric", "Questions", 1) in fake_st.events
    assert ("metric", "Accuracy", "0%") in fake_st.events
    assert any(event[0] == "expander" and "Question 1" in event[1] for event in fake_st.events)
    assert any(event[:2] == ("write", "**Correct answer:** A") for event in fake_st.events)
    assert ("markdown", "### Suggested Resource Materials") in fake_st.events
